apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::483361391347:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QR2FT0MJUNK4
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::483361391347:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-04T02:16:42Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1851"
  uid: b87418e5-133e-419e-920e-39a94aaa2658
